[2023-12-23 09:14:18,040 I 281468 281468] global_state_accessor.cc:374: This node has an IP address of 192.168.251.104, but we cannot find a local Raylet with the same address. This can happen when you connect to the Ray cluster with a different IP address or when connecting to a container.
[2023-12-23 09:14:18,260 I 152426 152426] global_state_accessor.cc:374: This node has an IP address of 192.168.251.105, but we cannot find a local Raylet with the same address. This can happen when you connect to the Ray cluster with a different IP address or when connecting to a container.
2023-12-23 09:14:23,423	INFO worker.py:1489 -- Connecting to existing Ray cluster at address: 192.168.251.101:6379...
2023-12-23 09:14:23,438	INFO worker.py:1673 -- Connected to Ray cluster.
Traceback (most recent call last):
  File "/data/asc24llama/zbtrs/ASC24-llama2/vllm-llama-test.py", line 4, in <module>
    llm = LLM(model = "/data/70B-chat-hf", tensor_parallel_size=2, pipeline_parallel_size=3)
  File "/data/asc24llama/zbtrs/ASC24-llama2/vllm/entrypoints/llm.py", line 105, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/data/asc24llama/zbtrs/ASC24-llama2/vllm/engine/llm_engine.py", line 266, in from_engine_args
    engine = cls(*engine_configs,
  File "/data/asc24llama/zbtrs/ASC24-llama2/vllm/engine/llm_engine.py", line 97, in __init__
    self._verify_args()
  File "/data/asc24llama/zbtrs/ASC24-llama2/vllm/engine/llm_engine.py", line 205, in _verify_args
    self.model_config.verify_with_parallel_config(self.parallel_config)
  File "/data/asc24llama/zbtrs/ASC24-llama2/vllm/config.py", line 207, in verify_with_parallel_config
    raise ValueError(
ValueError: Total number of hidden layers (80) must be divisible by pipeline parallel size (3).
srun: error: hepgpu1: task 0: Exited with exit code 1
